remote_theme: just-the-docs/just-the-docs
title: hhee4455 기술 블로그
description: 현명한 개발자가 되자
baseurl: "/" 
url: "https://hhee4455.github.io" 

aux_links:
  "hhee4455 GitHub":
    - "https://github.com/hhee4455"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/hhee4455/hhee4455.github.io"


search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'


color_scheme: dark


